// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtxIFev5h9ErPPcSIZkjUNTEAU4Cozlcw',
    appId: '1:1017817258095:web:6991e2d4b37d6b2264959a',
    messagingSenderId: '1017817258095',
    projectId: 'spotify-clone-6ed39',
    authDomain: 'spotify-clone-6ed39.firebaseapp.com',
    storageBucket: 'spotify-clone-6ed39.appspot.com',
    measurementId: 'G-21BFGB1XCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbtzM5qo_LCSSZs8cKrlGlxEdiY_w6sjw',
    appId: '1:1017817258095:android:55d6f6ae7a553adb64959a',
    messagingSenderId: '1017817258095',
    projectId: 'spotify-clone-6ed39',
    storageBucket: 'spotify-clone-6ed39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzdy2--uELMkN7xcnkK9EbpUfbS7u417k',
    appId: '1:1017817258095:ios:b2bc7bc48129cb2c64959a',
    messagingSenderId: '1017817258095',
    projectId: 'spotify-clone-6ed39',
    storageBucket: 'spotify-clone-6ed39.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzdy2--uELMkN7xcnkK9EbpUfbS7u417k',
    appId: '1:1017817258095:ios:b2bc7bc48129cb2c64959a',
    messagingSenderId: '1017817258095',
    projectId: 'spotify-clone-6ed39',
    storageBucket: 'spotify-clone-6ed39.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtxIFev5h9ErPPcSIZkjUNTEAU4Cozlcw',
    appId: '1:1017817258095:web:a035b09c704b4a3864959a',
    messagingSenderId: '1017817258095',
    projectId: 'spotify-clone-6ed39',
    authDomain: 'spotify-clone-6ed39.firebaseapp.com',
    storageBucket: 'spotify-clone-6ed39.appspot.com',
    measurementId: 'G-1GLJJEY599',
  );
}
